// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsoblfpvylpphozzbyzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzb2JsZnB2eWxwcGhvenpieXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDU0NTUsImV4cCI6MjA2MDMyMTQ1NX0.fT_rZBhgwjoHFjhDlPjCkFJCq4N1jgU_dBwtyUbx65k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);